<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_001_SignIn_Web_Admin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f9e00150-0fee-42ad-8956-26cb8e1e84ee</testSuiteGuid>
   <testCaseLink>
      <guid>d85a3c6c-b8c7-4a00-bc66-c986268404b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentication/TC_000_Admin_SignIn</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6c38f639-491b-43ee-a479-a564a1b49d4d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/SignInInvalid</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6c38f639-491b-43ee-a479-a564a1b49d4d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>dfe52a73-8f47-4da9-be3b-2d451353f5a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6c38f639-491b-43ee-a479-a564a1b49d4d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>2fb68b00-10a5-4f6a-82c5-bef78903bfdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6c38f639-491b-43ee-a479-a564a1b49d4d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status</value>
         <variableId>52dea0aa-cf75-4ce8-9e74-ccb565679a48</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
