<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_001_Auth</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f9e00150-0fee-42ad-8956-26cb8e1e84ee</testSuiteGuid>
   <testCaseLink>
      <guid>464afeb0-b427-4d62-8dbf-46333b76dbc2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/A_Authentication/TC_000_Admin_SignIn</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfe52a73-8f47-4da9-be3b-2d451353f5a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fb68b00-10a5-4f6a-82c5-bef78903bfdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52dea0aa-cf75-4ce8-9e74-ccb565679a48</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89e06bc7-eaba-46d0-8591-073916469518</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/A_Authentication/TC_001_Admin_SignIn _Invalid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b85f5934-af2a-4532-a055-fff6a9b0c749</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fd279de-e262-490f-a956-a679631d7e2d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb4e8c08-2618-46ca-b8b2-0a12ce6cec3c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/A_Authentication/TC_002_Admin_Mobile_Sign In</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8197ceb0-9843-4ba7-9b92-eb8ff1ea75b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcfd62cb-58de-4c47-a2d5-00c3a5d2dc93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>245d1b86-e4e3-45b8-8a69-a6ad44605771</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/A_Authentication/TC_003_Admin_Mobile_SignIn_Invalid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f3935d9-254c-4498-ae56-41df4b2e4ff8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68ea45bc-bee1-44d9-977a-f74f6c8a8e07</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
